# CITP

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go0.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics0.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go1.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics1.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go2.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics2.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go3.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics3.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go4.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics4.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go5.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics5.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go6.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics6.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go7.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics7.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go8.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics8.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go9.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics9.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go10.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics10.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go11.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics11.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go12.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics12.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go13.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics13.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go14.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics14.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go15.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics15.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"

# LIVJ

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go16.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics16.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go17.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics17.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go18.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics18.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go19.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics19.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go20.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics20.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go21.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics21.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go22.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics22.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go23.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics23.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go24.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics24.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go25.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics25.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go26.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics26.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go27.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics27.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go28.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics28.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go29.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics29.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go30.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics30.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/soc-livj.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go31.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics31.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"


# ORKUT

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go32.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics32.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go33.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics33.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go34.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics34.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go35.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics35.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go36.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics36.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go37.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics37.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go38.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics38.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go39.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics39.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go40.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics40.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go41.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics41.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go42.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics42.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go43.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics43.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go44.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics44.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go45.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics45.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go46.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics46.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/orkut.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go47.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics47.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"


# GPLUS

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go48.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics48.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go49.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics49.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go50.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics50.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go51.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics51.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go52.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics52.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go53.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics53.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go54.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics54.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go55.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics55.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go56.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics56.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go57.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics57.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go58.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics58.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.prMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go59.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics59.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go60.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics60.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go61.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics61.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go62.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics62.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderTwo -eip /user/ds256/a1/gplus.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go63.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics63.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"

for i in {0..48}
do
  hdfs dfs -ls /user/shriramr/giraph/metrics$i.txt | wc -l
done


cat t | while read line
do
   getYarnLog.sh $line > temp
   a=$(cat temp | grep "compute all partitions" | tr '\n' ' ' | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /\n/g' | awk '{ total += $1; count++ } END { print total/count }')
   b=$(cat temp | grep "network communication time" | tr '\n' ' ' | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /\n/g' | awk '{ total += $1; count++ } END { print total/count }')
   c=$(cat temp | grep "superstep time" | tr '\n' ' ' | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /\n/g' | awk '{ total += $1; count++ } END { print total/count }')
   echo $a $b $c >> temp1
done

cat t | while read line
do
   getYarnLog.sh $line > temp
   hdfs dfs -put temp /user/shriramr/logs/$line.log
done



