#!/bin/bash

# CITP
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output0.txt 24 > log0.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output1.txt 30 > log1.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output2.txt 36 > log2.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output3.txt 42 > log3.txt 

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output4.txt 24 > log4.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output5.txt 30 > log5.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output6.txt 36 > log6.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output7.txt 42 > log7.txt 

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output8.txt 24 0.01 0.85 > log8.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output9.txt 30 0.01 0.85 > log9.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output10.txt 36 0.01 0.85 > log10.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output11.txt 42 0.01 0.85 > log11.txt 

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output12.txt 24 1 > log12.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output13.txt 30 1 > log13.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output14.txt 36 1 > log14.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output15.txt 42 1 > log15.txt 

# LIVJ
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output16.txt 24 > log16.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output17.txt 30 > log17.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output18.txt 36 > log18.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output19.txt 42 > log19.txt 

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output20.txt 24 > log20.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output21.txt 30 > log21.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output22.txt 36 > log22.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output23.txt 42 > log23.txt 

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output24.txt 24 0.01 0.85 > log24.txt
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output25.txt 30 0.01 0.85 > log25.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output26.txt 36 0.01 0.85 > log26.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output27.txt 42 0.01 0.85 > log27.txt 

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output28.txt 24 1 > log28.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output29.txt 30 1 > log29.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output30.txt 36 1 > log30.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output31.txt 42 1 > log31.txt 

# ORKUT
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output32.txt 24 > log32.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output33.txt 30 > log33.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output34.txt 36 > log34.txt 
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output35.txt 42 > log35.txt 

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output36.txt 24 > log36.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output37.txt 30 > log37.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output38.txt 36 > log38.txt 
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output39.txt 42 > log39.txt 

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output40.txt 24 0.01 0.85 > log40.txt
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output41.txt 30 0.01 0.85 > log41.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output42.txt 36 0.01 0.85 > log42.txt 
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output43.txt 42 0.01 0.85 > log43.txt 

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output44.txt 24 1 > log44.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 5 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output45.txt 30 1 > log45.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 6 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output46.txt 36 1 > log46.txt 
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 7 --driver-memory 512m --executor-memory 8G --executor-cores 3  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/orkut.txt hdfs:///user/shriramr/output47.txt 42 1 > log47.txt 


