# CITP

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go0.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics0.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go1.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics1.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go2.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics2.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.wccG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go3.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics3.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 4 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go4.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics4.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 6 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go5.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics5.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 8 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go6.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics6.txt,giraph.logLevel=debug,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.conductanceG "--workers 10 -mc in.ds256.Assignment1.Giraph.masterCompute.conductanceMaster -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go7.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics7.txt,giraph.logLevel=debug,replicate=1 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go5.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics5.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go6.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics6.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go7.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics7.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.prG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go8.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics8.txt,giraph.logLevel=debug,tolerance=0.01,weight=0.85,replicate=0 -yh 12000"

runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 4 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go9.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics9.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 6 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go10.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics10.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 8 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go11.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics11.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"
runGiraphJob.sh /home/shriramr/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar in.ds256.Assignment1.Giraph.spanG "--workers 10 -eif in.ds256.Assignment1.Giraph.graphReader.graphReaderOne -eip /user/ds256/a1/cit-Patents.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /user/shriramr/giraph/go12.txt -ca giraph.pure.yarn.job=true,giraph.metrics.enable=true,giraph.metrics.directory=/user/shriramr/giraph/metrics12.txt,giraph.logLevel=debug,sourceId=1,replicate=1 -yh 12000"

# LIVJ

# ORKUT