#!/bin/bash

# CITP
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output0.txt 8 > log0.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output1.txt 16 > log1.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output2.txt 32 > log2.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output3.txt 64 > log3.txt &

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output4.txt 8 > log4.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output5.txt 16 > log5.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output6.txt 32 > log6.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output7.txt 64 > log7.txt &

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output8.txt 8 > log8.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output9.txt 16 > log9.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output10.txt 32 > log10.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output11.txt 64 > log11.txt &

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output12.txt 8 > log12.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output13.txt 16 > log13.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output14.txt 32 > log14.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/cit-Patents.txt hdfs:///user/shriramr/output15.txt 64 > log15.txt &

# LIVJ
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output16.txt 8 > log16.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output17.txt 16 > log17.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output18.txt 32 > log18.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output19.txt 64 > log19.txt &

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output20.txt 8 > log20.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output21.txt 16 > log21.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output22.txt 32 > log22.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output23.txt 64 > log23.txt &

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output24.txt 8 > log24.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output25.txt 16 > log25.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output26.txt 32 > log26.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output27.txt 64 > log27.txt &

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output28.txt 8 > log28.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output29.txt 16 > log29.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output30.txt 32 > log30.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/soc-livj.txt hdfs:///user/shriramr/output31.txt 64 > log31.txt &

# US-ROAD
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output32.txt 8 > log32.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output33.txt 16 > log33.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output34.txt 32 > log34.txt &
spark-submit --class in.ds256.Assignment1.Spark.wcc --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output35.txt 64 > log35.txt &

spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output36.txt 8 > log36.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output37.txt 16 > log37.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output38.txt 32 > log38.txt &
spark-submit --class in.ds256.Assignment1.Spark.conductance --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output39.txt 64 > log39.txt &

spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output40.txt 8 > log40.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output41.txt 16 > log41.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output42.txt 32 > log42.txt &
spark-submit --class in.ds256.Assignment1.Spark.pr --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output43.txt 64 > log43.txt &

spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 1 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output44.txt 8 > log44.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 2 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output45.txt 16 > log45.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 3 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output46.txt 32 > log46.txt &
spark-submit --class in.ds256.Assignment1.Spark.span --master yarn --deploy-mode cluster --num-executors 4 --driver-memory 512m --executor-memory 8G --executor-cores 4  Code/target/Assignment1-1.0-SNAPSHOT-jar-with-dependencies.jar hdfs:///user/ds256/a1/USA-road-d.USA.gr hdfs:///user/shriramr/output47.txt 64 > log47.txt &


